name: Add labels & assignees to PR's

on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    if: |
      startsWith(github.head_ref, 'feat/') ||
      startsWith(github.head_ref, 'fix/') ||
      startsWith(github.head_ref, 'chore/') ||
      startsWith(github.head_ref, 'test/')
    runs-on: ubuntu-latest
    steps:
      - name: Auto label
        uses: TimonVS/pr-labeler-action@v4
        with:
          configuration-path: .github/configs/auto_label.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Auto assign
        uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          configuration-path: .github/configs/auto_assign.yml
